trigger:
- master
stages:
- stage: build
  jobs:
  - job: build
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'npm install'
      inputs:
        workingDir: '.'
        command: install

    - task: Npm@1
      displayName: 'npm build'
      inputs:
        workingDir: '.'
        command: custom
        customCommand: run-script build

    - task: CopyFiles@2
      displayName: 'Copy Files'
      inputs:
        SourceFolder: 'build'
        TargetFolder: '$(build.artifactstagingdirectory)'
        CleanTargetFolder: true
